### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by Smery55** [Coffeelot/cw-darkweb#3]
I use your script 

he is so cool. 
i conveted this one to esx but know with new update

I don’t know how to convert corrctly can tou do this for esx ?

**Comment by Coffeelot** [comment]
ESX is not planned right now.

Maybe in the far future.

**Comment by Smery55** [comment]
If I do it i send you my version of your script. 
Are you ok ?

**Comment by Coffeelot** [comment]
[Racingapp ](https://github.com/Coffeelot/cw-racingapp/) will get a new release where I've created a separate file for core-dependent actions. If that works out well then this script will probably get a similar style setup which would make the conversion easier.

However; this might take some time as it's not a current priority. If you'd like this prioritized feel free to strike up a conversation about a commission via Discord DMs.
